env:
  - DISPLAY=:99.0

before_install:
  - "sudo pip install -r requirements.txt"
  - "npm install -g npm && npm install"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - 'cp -r vendor/ol3/src/ol src'
  - 'cp -r vendor/schedul-math-js/src/schedul src'

script:
  - "mkdir build"
  - "node tasks/generate-requires.js `find test/spec | grep \.js$` > build/test_requires.js"
  - "node tasks/test.js"
  - "node tasks/build.js config/geographiclib.json build/geographiclib.min.js"
